name: auto_deploy_to_production
'on':
  pull_request:
    branches:
      - Develop
jobs:
  deploy_to_production:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          git fetch --prune --unshallow
      - name: prepare_deploy_data
        shell: bash
        run: >
          echo ${{ secrets.SFDC_STAG_AUTH_URL }} > ./SFDC_STAG_AUTH_URL.txt

          echo "files_to_deploy=$(git --no-pager diff --name-only
          --diff-filter=d origin/${{ github.base_ref }} -- force-app | tr '\n'
          ',' | sed 's/,/, /g' | sed 's/\(.*\),/\1 /')" >> $GITHUB_ENV
      - name: authenticate_to_production
        uses: marcelblijleven/salesforcedx-actions@master
        with:
          args: >-
            force:auth:sfdxurl:store --sfdx-url-file=./SFDC_STAG_AUTH_URL.txt
            --alias=develop
      - name: deploy_files
        uses: marcelblijleven/salesforcedx-actions@master
        with:
          args: >-
            force:source:deploy -p force-app -u ${{ secrets.SFDX_AUTH_USERNAME}} -l RunLocalTests
      - run: '$([ $? -eq 0 ]  || exit 1)'
